"""Transparent model primitives introduced phase by phase."""

from sebgpt.model.embeddings import (
    EmbeddingContractError,
    EmbeddingTypeError,
    TokenPositionEmbedding,
)
from sebgpt.model.phase4_corpus import load_phase4_permitted_corpus
from sebgpt.model.phase4_experiment import (
    AggregateMeasurement,
    Phase4ExperimentConfig,
    Phase4ExperimentResult,
    Phase4PermittedCorpus,
    TrainingPassResult,
    load_phase4_experiment_config,
    measure_aggregate_loss,
    run_fixed_phase4_experiment,
    run_training_pass,
    validate_phase4_experiment_preflight,
)
from sebgpt.model.self_attention import (
    AttentionContractError,
    AttentionInspection,
    AttentionNumericalError,
    AttentionTypeError,
    MultiHeadCausalSelfAttention,
    SingleHeadCausalSelfAttention,
)
from sebgpt.model.simple_language_model import (
    Phase4ContractError,
    Phase4GovernanceError,
    Phase4TypeError,
    SimpleNeuralLanguageModel,
    clear_gradients,
    explicit_cross_entropy,
    manual_sgd_step,
    measure_example_loss,
    model_parameter_digest,
    probabilities_from_logits,
    scale_backward_loss,
)
from sebgpt.model.transformer_block import (
    DropoutInspection,
    ExplicitDropout,
    ExplicitLayerNorm,
    FeedForwardInspection,
    LayerNormInspection,
    PositionwiseFeedForward,
    TransformerBlock,
    TransformerBlockContractError,
    TransformerBlockInspection,
    TransformerBlockNumericalError,
    TransformerBlockTransactionError,
    TransformerBlockTypeError,
    explicit_gelu,
)


__all__ = [
    "AttentionContractError",
    "AttentionInspection",
    "AttentionNumericalError",
    "AttentionTypeError",
    "EmbeddingContractError",
    "EmbeddingTypeError",
    "DropoutInspection",
    "ExplicitDropout",
    "ExplicitLayerNorm",
    "FeedForwardInspection",
    "LayerNormInspection",
    "AggregateMeasurement",
    "Phase4ContractError",
    "Phase4ExperimentConfig",
    "Phase4ExperimentResult",
    "Phase4GovernanceError",
    "Phase4PermittedCorpus",
    "Phase4TypeError",
    "PositionwiseFeedForward",
    "MultiHeadCausalSelfAttention",
    "SimpleNeuralLanguageModel",
    "SingleHeadCausalSelfAttention",
    "TokenPositionEmbedding",
    "TrainingPassResult",
    "TransformerBlock",
    "TransformerBlockContractError",
    "TransformerBlockInspection",
    "TransformerBlockNumericalError",
    "TransformerBlockTransactionError",
    "TransformerBlockTypeError",
    "clear_gradients",
    "explicit_cross_entropy",
    "explicit_gelu",
    "load_phase4_experiment_config",
    "load_phase4_permitted_corpus",
    "manual_sgd_step",
    "measure_example_loss",
    "measure_aggregate_loss",
    "model_parameter_digest",
    "probabilities_from_logits",
    "run_fixed_phase4_experiment",
    "run_training_pass",
    "scale_backward_loss",
    "validate_phase4_experiment_preflight",
]
